name: certificates

# TODO
# run on a schedule
on:
  push:
    branches:
      - certs


jobs:
  renew-certificate:
    runs-on: ubuntu-18.04
    steps:
      - name: Posh-ACME
        run: echo "TODO - run bin/certs.clj"
